### ISSUE TITLE
(가능한 분에게) GameController에 게임 종류 저장 기능 추가

### ISSUE THREAD

**Issue by eaglclaws** [eaglclaws/OSSPT10-SNAKE#12]
GameController에 SOLO, DUAL, AUTO1, AUTO2인지를 저장하여, GameFactory에서 Game 객체를 생성하는데 활용할 수 있도록 해주어야합니다.

**Comment by jaeminld** [comment]
GameController에 players 변수에 single game, auto game 이면 1, dual game이면 2라고 저장해주어야 합니다.
