### ISSUE TITLE
GameScene의 BOARD_WIDTH, BOARD_HEIGHT 의존성 제거

### ISSUE THREAD

**Issue by eaglclaws** [eaglclaws/OSSPT10-SNAKE#14]
현재 보드의 크기를 정의하고 있는 define 2개가 있습니다. #13 처럼 활용할 수 있게 메크로가 아닌 const 변수로 바꿉니다.

**Comment by jaeminld** [comment]
Game.h에 virtual int get_board_height()와 virtual int get_board_width()을 추가해서 사용하면 될까요?
