### ISSUE TITLE
apple_place관련해서 제안드립니다. 

### ISSUE THREAD

**Issue by jaeminld** [eaglclaws/OSSPT10-SNAKE#15]
place_apple()인자로 난수 값을 주는데 apple_place()자체에서 난수를 생성해서 하는 것이 더 괜찮지 않을지 제안드립니다. 
다른 Game에서는 apple이 1개인 반면 DualGame에서는 apple이 2개인 문제를 해결하기 위함입니다.

**Comment by eaglclaws** [comment]
동의합니다. 일단 SoloGame과 충돌을 막기 위해 Game.h에 새로운 virtual bool place_apple()을 추가 해주시면 될 듯합니다.
