### ISSUE TITLE
Game내에 AutoGame 구현 시에 필요 없는 부분이 순수 가상함수로 선언된 것을 확인했습니다.

### ISSUE THREAD

**Issue by alsgur7859** [eaglclaws/OSSPT10-SNAKE#18]
auto game에는 save기능이 없고 그래서 load 기능도 필요 없습니다.
따라서 export_board, export_snake, export_dir 이 세 가지 save에 필요한 기능은 game.h에서 지워야 할 것 같습니다.
마찬가지로 load 함수도 game.h에서 지워야 할 것 같습니다.

**Comment by alsgur7859** [comment]
keyevent도 지워야 할 거 같아요!

**Comment by eaglclaws** [comment]
하지만 싱글과 듀얼에서는 필요하죠. 오토에서 동작할 필요없는 부분은 그냥 비어 있는 함수로 만들거나 호출했을 때 에러 띠우게 하는 것이 낫습니다. 아예 삭제하면 싱글과 듀얼 워크플로우에 문제가 생깁니다.

**Comment by alsgur7859** [comment]
아 그렇게도 가능하면 그렇게 해도 좋을 거 같아요! virtual로 선언 된 함수 중의 정의가 되지 않은 함수를 재정의하지 않으면 문제가 되는 줄 알고 저렇게 올렸습니다!
