### ISSUE TITLE
EnumList class 생성 제안입니다. 

### ISSUE THREAD

**Issue by jaeminld** [eaglclaws/OSSPT10-SNAKE#25]
Enum이 전부 퍼져 있어서 하나로 모으는 보기 쉽게 header를 생성하겠습니다.

**Comment by eaglclaws** [comment]
좋습니다. 싱글턴으로 만드실 예정이신가요? 만드신 후에 저희가 각자 파트에서 리팩토링 할 수 있도록 스펙 정의 부탁드려요~

**Comment by jaeminld** [comment]
기존에 있던 board_dir, board_elements, game_state, key_press가 들어가고
제가 나중에 만든 PlayerSelect가 나열될 예정입니다!

**Comment by eaglclaws** [comment]
아마 완성 하고서 빌드 테스트 하면 재정의 에러 엄청 나올거에요. 일일이 헤더 찾아 가서 기존 정의를 지워 주셔야해요. 아니면 문제 일으키는 파일들 나열해서 이슈로 올려주세요. 저희가 순차적으로 가능한 것 처리해 나갈게요.
