### ISSUE TITLE
GameScene 기존 sprites가 vector일 때 오류나서 수정했습니다. 

### ISSUE THREAD

**Issue by jaeminld** [eaglclaws/OSSPT10-SNAKE#27]
vector reserve()를 사용하면 실행이 안되서
sprites = new std::vector<std::vector<Sprite*>>(bheight);
for (int i = 0; i < bheight; i++) sprites->at(i) = std::vector<Sprite*>(bwidth);
로 임시로 변경하고 사용하겠습니다.

**Comment by eaglclaws** [comment]
그 부분은 제 실수가 있었네요. 빌드 테스트를 못해서 미처 확인 못했습니다. 다음 커밋 때 수정하겠습니다.
